# -*- coding: utf-8 -*-
"""Housing_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HlT32rTNVKP5ROWpT5Oxq4O9xR15T8zq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(color_codes=True)

housing_df= pd.read_csv('raw_house_data.csv')

housing_df

housing_df.columns

housing_df.shape

housing_df.info

housing_df.describe()

housing_df.hist(bins=50, figsize=(20,15))

h=housing_df.HOA

counts=h.value_counts()
counts

housing_df

housing_df= housing_df.rename(columns={"size(sqft)":"sqft"})
housing_df

s=housing_df.sqft
counts=s.value_counts
counts

housing_df.plot(kind="scatter",x="longitude",y="latitude")

sns.pairplot(housing_df)

corr_matrix= housing_df.corr()
corr_matrix["price"].sort_values(ascending=False)

housing_df.isnull()

housing_df.plot(kind="scatter",x="zipcode",y="bedroom")